services:
  - type: web
    name: email-phishing-detector
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements.txt
    startCommand: cd backend && PYTHONPATH=/opt/render/project/src uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ALLOWED_ORIGINS
        value: https://email-phishing-detector.onrender.com
      - key: PYTHONPATH
        value: /opt/render/project/src

